<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <OutputType>Library</OutputType>
    <IsPackable>false</IsPackable>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <SonarQubeTestProject>false</SonarQubeTestProject>
    <NoWarn>1591;NU1608</NoWarn>
  </PropertyGroup>
  <ItemGroup>
    <Compile Remove="dist\**" />
    <Content Remove="dist\**" />
    <EmbeddedResource Remove="dist\**" />
    <None Remove="dist\**" />
  </ItemGroup>
  <ItemGroup>
    <Content Update="Localizations\**">
      <CopyToPublishDirectory>Never</CopyToPublishDirectory>
    </Content>
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\VirtoCommerce.UCP.Core\VirtoCommerce.UCP.Core.csproj" />
    <ProjectReference Include="..\VirtoCommerce.UCP.Data\VirtoCommerce.UCP.Data.csproj" />
    <ProjectReference Include="..\VirtoCommerce.UCP.ExperienceApi\VirtoCommerce.UCP.ExperienceApi.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="VirtoCommerce.ApplicationInsights.Core" Version="3.1005.0" />
    <PackageReference Include="ModelContextProtocol.AspNetCore" Version="1.4.0" />
    <PackageReference Include="Swashbuckle.AspNetCore.SwaggerGen" Version="10.2.3" PrivateAssets="all" ExcludeAssets="runtime" />
    <PackageReference Include="VirtoCommerce.XCatalog.Core" Version="3.1023.0" />
    <PackageReference Include="VirtoCommerce.XCatalog.Data" Version="3.1023.0" />
    <PackageReference Include="VirtoCommerce.XCart.Core" Version="3.1038.0" />
    <PackageReference Include="VirtoCommerce.XCart.Data" Version="3.1038.0" />
    <PackageReference Include="VirtoCommerce.XOrder.Data" Version="3.1013.0" />
  </ItemGroup>
  <ItemGroup>
    <Content Include="module.manifest" CopyToOutputDirectory="PreserveNewest" CopyToPublishDirectory="PreserveNewest" />
  </ItemGroup>
  <ItemGroup>
    <InternalsVisibleTo Include="VirtoCommerce.UCP.Tests" />
  </ItemGroup>
</Project>
