<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <SonarQubeTestProject>false</SonarQubeTestProject>
  </PropertyGroup>
  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
    <PackageReference Include="VirtoCommerce.OrdersModule.Core" Version="3.1000.0" />
    <PackageReference Include="VirtoCommerce.Platform.Core" Version="3.1066.0-alpha.13384-vcst-5378-unified-buyer-flow" />
    <PackageReference Include="VirtoCommerce.StoreModule.Core" Version="3.1004.0" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\VirtoCommerce.UCP.Core\VirtoCommerce.UCP.Core.csproj" />
  </ItemGroup>
</Project>
